image rocker/geospatial:latest

before_script:
  - R -e "install.packages('blogdown',repos='http://cran.rstudio.com')"
  - R -e "blogdown::install_hugo()"

pages:
  script:
    - R -e "setwd('blog')"
    - R -e "blogdown::build_site()"
  artifacts:
    paths:
      - blog/public
  only:
    - master
